version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4019
      POSTGRES_DB: go_chat
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  server:
    build: .
    ports:
      - "8040:8040"
    depends_on:
      - postgres
      - redis
    environment:
      DB_DSN: postgres://postgres:4019@postgres:5432/go_chat?sslmode=disable
      REDIS_DSN: redis://redis:6379
      HTTP_PORT: 8040
      JWT_SECRET: supersecretkey

volumes:
  pgdata: